package com.carroll.gameplan.model;

import jakarta.persistence.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a type or category of equipment.
 * <p>
 * Each EquipmentType defines a category (e.g., "Basketball Hoop", "Camera")
 * and can have multiple {@link Equipment} instances associated with it.
 * </p>
 *
 * <p>
 * The {@code fieldSchema} stores a JSON structure that defines dynamic attributes
 * for this equipment type. This allows flexible, schema-driven attribute definitions.
 * </p>
 *
 * <p><b>Example fieldSchema:</b></p>
 * <pre>
 * {
 *   "size": { "options": ["S", "M", "L"] },
 *   "color": { "options": ["red", "blue"] }
 * }
 * </pre>
 */
@Entity
public class EquipmentType {

    /**
     * Primary key for the equipment type.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique name of the equipment type.
     * <p>
     * This value must be unique and cannot be null.
     * Example: "Basketball Hoop"
     * </p>
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * JSON schema defining dynamic attributes for this equipment type.
     * <p>
     * Stored as a JSON string in the database.
     * Used to determine valid attributes and their allowed values.
     * </p>
     */
    @Column(columnDefinition = "json")
    private String fieldSchema;

    /**
     * List of equipment items that belong to this type.
     * <p>
     * One EquipmentType can have many Equipment entities.
     * </p>
     */
    @OneToMany(mappedBy = "equipmentType")
    private List<Equipment> equipmentList;

    /**
     * Color associated with this equipment type.
     * <p>
     * Used primarily for UI display (e.g., "#FF5733" or "blue").
     * </p>
     */
    @Column
    private String color;

    /**
     * Default constructor required by JPA.
     */
    public EquipmentType() {
    }

    /**
     * Constructor to create an EquipmentType.
     *
     * @param name        Unique name of the equipment type
     * @param fieldSchema JSON schema defining attributes
     * @param color       Optional UI color
     */
    public EquipmentType(String name, String fieldSchema, String color) {
        this.name = name;
        this.fieldSchema = fieldSchema;
        this.color = color;
    }

    /**
     * Retrieves the list of allowed options for a given attribute
     * from the JSON field schema.
     * <p>
     * If the attribute exists and has an "options" array,
     * those values are returned. Otherwise, an empty list is returned.
     * </p>
     *
     * <p><b>Example:</b></p>
     * If schema contains:
     * <pre>
     * { "size": { "options": ["S", "M", "L"] } }
     * </pre>
     * Calling {@code getAttributeOptions("size")} returns:
     * ["S", "M", "L"]
     *
     * @param attributeName Name of the attribute to look up
     * @return List of allowed option values, or empty list if none found
     */
    public List<String> getAttributeOptions(String attributeName) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode schema = mapper.readTree(fieldSchema);
            JsonNode attrNode = schema.get(attributeName);
            if (attrNode != null && attrNode.has("options")) {
                List<String> options = new ArrayList<>();
                attrNode.get("options").forEach(n -> options.add(n.asString()));
                return options;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return List.of();
    }

    // ===== Getters =====

    /**
     * Gets the ID of the equipment type.
     *
     * @return equipment type ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name of the equipment type.
     *
     * @return equipment type name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the equipment type.
     *
     * @param name equipment type name
     */
    public void setName(String name) {
        this.name = name;
    }

    // ===== Setters =====

    /**
     * Gets the JSON field schema.
     *
     * @return JSON schema string
     */
    public String getFieldSchema() {
        return fieldSchema;
    }

    /**
     * Sets the JSON field schema.
     *
     * @param fieldSchema JSON schema string
     */
    public void setFieldSchema(String fieldSchema) {
        this.fieldSchema = fieldSchema;
    }

    /**
     * Gets the list of equipment associated with this type.
     *
     * @return list of equipment
     */
    public List<Equipment> getEquipmentList() {
        return equipmentList;
    }

    /**
     * Sets the list of equipment for this type.
     *
     * @param equipmentList list of equipment
     */
    public void setEquipmentList(List<Equipment> equipmentList) {
        this.equipmentList = equipmentList;
    }

    /**
     * Gets the color associated with this equipment type.
     *
     * @return color string
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the color associated with this equipment type.
     *
     * @param color color string
     */
    public void setColor(String color) {
        this.color = color;
    }
}