package edu.carroll.gameplan.model;

import jakarta.persistence.*;

import java.util.List;
import java.util.Objects;

/**
 * Entity representing a piece of equipment that can be reserved by users.
 * <p>
 * Each Equipment has a name, status, and belongs to an {@link EquipmentType}.
 * It may also have associated reservations and optional attributes.
 * </p>
 */
@Entity
public class Equipment {

    /**
     * Primary key for the equipment entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Current status of the equipment (e.g., AVAILABLE, RESERVED).
     * Stored as a string representation of the enum.
     */
    @Enumerated(EnumType.STRING)
    private EquipmentStatus status;

    /**
     * Name of the equipment.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The type/category of this equipment.
     * <p>
     * Many equipment items can belong to one EquipmentType.
     * This relationship is required.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "equipment_type_id", nullable = false)
    private EquipmentType equipmentType;

    /**
     * List of reservations associated with this equipment.
     * <p>
     * One equipment can have many reservations.
     * Cascade ALL ensures operations propagate, and orphanRemoval ensures
     * removed reservations are deleted from the database.
     * </p>
     */
    @OneToMany(mappedBy = "equipment", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Reservation> reservations;

    /**
     * Optional attributes for the equipment (e.g., size, color).
     * <p>
     * One equipment can have many attributes.
     * Cascade ALL ensures attributes are persisted/removed with the equipment.
     * </p>
     */
    @OneToMany(mappedBy = "equipment", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<EquipmentAttribute> attributes;

    /**
     * Default constructor required by JPA.
     */
    public Equipment() {
    }

    // ===== Getters & Setters =====

    /**
     * Gets the equipment ID.
     *
     * @return equipment ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the equipment ID.
     *
     * @param id equipment ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the current status of the equipment.
     *
     * @return equipment status
     */
    public EquipmentStatus getStatus() {
        return status;
    }

    /**
     * Sets the status of the equipment.
     *
     * @param status equipment status
     */
    public void setStatus(EquipmentStatus status) {
        this.status = status;
    }

    /**
     * Gets the name of the equipment.
     *
     * @return equipment name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the equipment.
     *
     * @param name equipment name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the equipment type.
     *
     * @return associated EquipmentType
     */
    public EquipmentType getEquipmentType() {
        return equipmentType;
    }

    /**
     * Sets the equipment type.
     *
     * @param equipmentType associated EquipmentType
     */
    public void setEquipmentType(EquipmentType equipmentType) {
        this.equipmentType = equipmentType;
    }

    /**
     * Gets the list of reservations for this equipment.
     *
     * @return list of reservations
     */
    public List<Reservation> getReservations() {
        return reservations;
    }

    /**
     * Sets the list of reservations for this equipment.
     *
     * @param reservations list of reservations
     */
    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

    /**
     * Gets the list of attributes for this equipment.
     *
     * @return list of attributes
     */
    public List<EquipmentAttribute> getAttributes() {
        return attributes;
    }

    /**
     * Sets the list of attributes for this equipment.
     *
     * @param attributes list of attributes
     */
    public void setAttributes(List<EquipmentAttribute> attributes) {
        this.attributes = attributes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Equipment that)) {
            return false;
        }
        return Objects.equals(normalizeName(name), normalizeName(that.name))
                && Objects.equals(typeName(equipmentType), typeName(that.equipmentType));
    }

    @Override
    public int hashCode() {
        return Objects.hash(normalizeName(name), typeName(equipmentType));
    }

    private String normalizeName(String value) {
        return value == null ? null : value.trim();
    }

    private String typeName(EquipmentType type) {
        return type == null ? null : normalizeName(type.getName());
    }
}
