package edu.carroll.gameplan.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.util.Objects;

/**
 * Entity representing an attribute of a piece of equipment.
 * <p>
 * Each attribute is a simple name-value pair (e.g., "size" = "M").
 * Attributes are associated with a specific {@link Equipment}.
 * </p>
 */
@Entity
public class EquipmentAttribute {

    /**
     * Primary key for the attribute.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the attribute (e.g., "size", "color").
     */
    private String name;

    /**
     * Value of the attribute (e.g., "M", "red").
     */
    @Column(name = "attribute_value")
    private String value;

    /**
     * The equipment this attribute belongs to.
     * <p>
     * Many attributes can belong to one piece of equipment.
     * {@link JsonIgnore} prevents infinite recursion when serializing.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "equipment_id")
    @JsonIgnore
    private Equipment equipment;

    /**
     * Default constructor required by JPA.
     */
    public EquipmentAttribute() {
    }

    /**
     * Gets the attribute ID.
     *
     * @return attribute ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the attribute name.
     *
     * @return attribute name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the attribute name.
     *
     * @param name attribute name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the attribute value.
     *
     * @return attribute value
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the attribute value.
     *
     * @param value attribute value
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the associated equipment.
     *
     * @return equipment entity
     */
    public Equipment getEquipment() {
        return equipment;
    }

    /**
     * Sets the associated equipment.
     *
     * @param equipment equipment entity
     */
    public void setEquipment(Equipment equipment) {
        this.equipment = equipment;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof EquipmentAttribute that)) {
            return false;
        }
        return Objects.equals(name, that.name)
                && Objects.equals(value, that.value)
                && Objects.equals(ownerKey(equipment), ownerKey(that.equipment));
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, value, ownerKey(equipment));
    }

    private String ownerKey(Equipment value) {
        if (value == null) {
            return null;
        }
        String typeName = value.getEquipmentType() != null ? value.getEquipmentType().getName() : null;
        String equipmentName = value.getName();
        String normalizedEquipmentName = equipmentName == null ? null : equipmentName.trim();
        String normalizedTypeName = typeName == null ? null : typeName.trim();
        if (normalizedEquipmentName == null && normalizedTypeName == null) {
            return null;
        }
        return (normalizedEquipmentName == null ? "" : normalizedEquipmentName)
                + "|"
                + (normalizedTypeName == null ? "" : normalizedTypeName);
    }
}
